### ISSUE TITLE
type chinese repate 2 times

### ISSUE THREAD

**Issue by abigmiu** [m1911star/affine-client#1]
When I type Chinese, it repeats twice
with englisth, its no problem 

![Video_22-08-07_12-40-01_](https://user-images.githubusercontent.com/43983920/183275564-3ae5107e-d927-4dbb-9d2e-1af918e024c5.gif)

**Comment by m1911star** [comment]
I'll check the issue later. thanks～

**Comment by m1911star** [comment]
> When I type Chinese, it repeats twice with englisth, its no problem
> 
> ![Video_22-08-07_12-40-01_](https://user-images.githubusercontent.com/43983920/183275564-3ae5107e-d927-4dbb-9d2e-1af918e024c5.gif) [ ![Video_22-08-07_12-40-01_](https://user-images.githubusercontent.com/43983920/183275564-3ae5107e-d927-4dbb-9d2e-1af918e024c5.gif) ](https://user-images.githubusercontent.com/43983920/183275564-3ae5107e-d927-4dbb-9d2e-1af918e024c5.gif) [ ](https://user-images.githubusercontent.com/43983920/183275564-3ae5107e-d927-4dbb-9d2e-1af918e024c5.gif)

Hi, I just find a related issue with slate, still working on how to fix it. Sorry for the issue~
https://github.com/ianstormtaylor/slate/issues/5023
