### ISSUE TITLE
dlopen(): error loading libfuse.so.2  AppImages require FUSE to run.

### ISSUE THREAD

**Issue by learn2021-coder** [m1911star/affine-client#10]
when i run the app,it show me the error

```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run.
```
i run 
`yay -S fuse2`
solved it!

Anway,thanks for your nice work!

**Comment by m1911star** [comment]
@learn2021-coder  Are you using arch linux? Since I dont have a arch machine, would you please post a pr to update the readme for arch user guide? Thanks~

**Comment by learn2021-coder** [comment]
> @learn2021-coder Are you using arch linux? Since I dont have a arch machine, would you please post a pr to update the readme for arch user guide? Thanks~

要在哪里提交呢？

**Comment by m1911star** [comment]
> > @learn2021-coder Are you using arch linux? Since I dont have a arch machine, would you please post a pr to update the readme for arch user guide? Thanks~
> 
> 要在哪里提交呢？

Create a new branch on GitHub, add the documentation, and submit a pull request

**Comment by learn2021-coder** [comment]
我查了下，fuse2这东西，很多软件都包含它，https://archlinux.org/packages/extra/x86_64/fuse2/

archlinux也不需要特别安装，直接用打包好的AppImage格式就可以了。什么时候有人打包的话，再写不迟。

**Comment by m1911star** [comment]
already update the readme doc, thanks~
