### ISSUE TITLE
Install failed In windows 10.

### ISSUE THREAD

**Issue by mitsuhatu** [m1911star/affine-client#8]
An irreversible error has occurred when install desk app with msi in windows 10.

![image](https://user-images.githubusercontent.com/110213079/185417026-4a205169-a394-4e00-a998-548df125ba0b.png)

In addition, can you provide a Chinese msi?

If you fix it , please tell me, thx.

**Comment by mitsuhatu** [comment]
Current user feedback it's ok when he replace an new PC to install.

**Comment by m1911star** [comment]
ah, ok, thanks for your comment and sorry for late reply~

> Current user feedback it's ok when he replace an new PC to install.

**Comment by m1911star** [comment]
It's related to his company security strategy. After turning off, the installation has completed. Close this issue.
